# Generated by Django 2.2.5 on 2019-09-11 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_duplicated_reserved_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='python_pythonpublication', serialize=False, to='core.Publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='PythonRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='python_pythonremote', serialize=False, to='core.Remote')),
                ('prereleases', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='PythonPackageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='python_pythonpackagecontent', serialize=False, to='core.Content')),
                ('filename', models.TextField(db_index=True, unique=True)),
                ('packagetype', models.TextField(choices=[('bdist_dmg', 'bdist_dmg'), ('bdist_dumb', 'bdist_dumb'), ('bdist_egg', 'bdist_egg'), ('bdist_msi', 'bdist_msi'), ('bdist_rpm', 'bdist_rpm'), ('bdist_wheel', 'bdist_wheel'), ('bdist_wininst', 'bdist_wininst'), ('sdist', 'sdist')])),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('metadata_version', models.TextField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('home_page', models.TextField()),
                ('download_url', models.TextField()),
                ('author', models.TextField()),
                ('author_email', models.TextField()),
                ('maintainer', models.TextField()),
                ('maintainer_email', models.TextField()),
                ('license', models.TextField()),
                ('requires_python', models.TextField()),
                ('project_url', models.TextField()),
                ('platform', models.TextField()),
                ('supported_platform', models.TextField()),
                ('requires_dist', models.TextField(default='[]')),
                ('provides_dist', models.TextField(default='[]')),
                ('obsoletes_dist', models.TextField(default='[]')),
                ('requires_external', models.TextField(default='[]')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('filename',)},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PythonDistribution',
            fields=[
                ('basedistribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='python_pythondistribution', serialize=False, to='core.BaseDistribution')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='python_pythondistribution', to='core.Publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.basedistribution',),
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('python_package_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', related_query_name='classifier', to='python.PythonPackageContent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSpecifier',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('version_specifier', models.TextField(default='')),
                ('exclude', models.BooleanField(default=False)),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='projectspecifier', to='python.PythonRemote')),
            ],
            options={
                'unique_together': {('name', 'version_specifier', 'exclude', 'remote')},
            },
        ),
    ]
