# Generated by Django 2.2.6 on 2019-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifier',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='classifier',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='classifier',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='projectspecifier',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='projectspecifier',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='projectspecifier',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
    ]
