# Generated by Django 2.2.9 on 2020-05-17 09:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackagecontent',
            name='classifiers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Classifier',
        ),
    ]
