# Generated by Django 2.2.18 on 2021-02-17 03:48

from django.db import migrations, models
import django.db.models.deletion


def migrate_distribution_fields(apps, schema_editor):
    # Set the core "_publication" field with the value of the detail "publication" field
    PythonDistribution = apps.get_model('python', 'pythondistribution')

    distributions = list(PythonDistribution.objects.all())

    for distribution in distributions:
        distribution._publication = distribution.publication

    PythonDistribution.objects.bulk_update(distributions, ['_publication'])

class Migration(migrations.Migration):

    dependencies = [
        ('python', '0002_pythonpackagecontent_python_version'),
        ('core', '0060_add_new_distribution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPublishSettings',
            fields=[
                ('publishsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='python_pythonpublishsettings', serialize=False, to='core.PublishSettings')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publishsettings',),
        ),
        migrations.RunPython(migrate_distribution_fields),
        migrations.RemoveField(
            model_name='pythondistribution',
            name='publication',
        ),
    ]
