# Generated by Django 2.2.6 on 2019-10-10 04:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0002_pulp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='obsoletes_dist',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='provides_dist',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='requires_dist',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pythonpackagecontent',
            name='requires_external',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
