# Generated by Django 3.2.8 on 2021-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0010_update_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonrepository',
            name='last_serial',
            field=models.IntegerField(default=0),
        ),
    ]
