# Generated by Django 4.2.5 on 2023-10-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python", "0011_alter_pythondistribution_distribution_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonremote",
            name="sync_dependencies",
            field=models.BooleanField(default=False),
        ),
    ]
