# Generated by Django 4.2.10 on 2024-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0013_add_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonpackagecontent',
            name='dynamic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
