# Generated by Django 4.2.23 on 2025-08-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0014_pythonpackagecontent_dynamic_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pythonpackagecontent",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("upload_python_packages", "Can upload Python packages using synchronous API.")
                ],
            },
        ),
    ]
