# Generated by Django 4.2.25 on 2025-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0015_alter_pythonpackagecontent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonpackagecontent",
            name="metadata_sha256",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
