# Generated by Django 4.2.25 on 2025-10-31 12:50

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_domainize_import_export"),
        ("python", "0015_alter_pythonpackagecontent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagePermissionGuard",
            fields=[
                (
                    "contentguard_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.contentguard",
                    ),
                ),
                (
                    "download_policy",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary mapping package names to lists of user/group PRNsthat are allowed to download those packages.",
                    ),
                ),
                (
                    "upload_policy",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary mapping package names to lists of user/group PRNsthat are allowed to upload those packages.",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "manage_roles_packagepermissionguard",
                        "Can manage role assignments on package permission guard",
                    )
                ],
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.contentguard", pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
