# Generated by Django 4.2.24 on 2025-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0015_alter_pythonpackagecontent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonpackagecontent",
            name="metadata_sha256",
            field=models.CharField(null=True, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pythonpackagecontent",
            name="yanked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pythonpackagecontent",
            name="yanked_reason",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
