# Generated by Django 4.2.26 on 2025-12-01 19:49

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0017_pythonpackagecontent_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageProvenance",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("provenance", models.JSONField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "_pulp_domain",
                    models.ForeignKey(
                        default=pulpcore.app.util.get_domain_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.domain",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenances",
                        to="python.pythonpackagecontent",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("sha256", "_pulp_domain")},
            },
            bases=("core.content",),
        ),
        migrations.AddField(
            model_name="pythonremote",
            name="provenance",
            field=models.BooleanField(default=False),
        ),
    ]
