# Generated by Django 4.2.26 on 2025-11-13 21:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0018_packageprovenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonremote",
            name="project_metadata",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProjectMetadataContent",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("project_name", models.TextField()),
                (
                    "tracks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "alternate_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                (
                    "_pulp_domain",
                    models.ForeignKey(
                        default=pulpcore.app.util.get_domain_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.domain",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("sha256", "_pulp_domain")},
            },
            bases=("core.content",),
        ),
    ]
