# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_python' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

import argparse
import re
import os
import textwrap

from git import Repo


release_path = os.path.dirname(os.path.abspath(__file__))
plugin_path = release_path.split("/.ci")[0]

plugin_name = "pulp_python"
version = None
with open(f"{plugin_path}/setup.py") as fp:
    for line in fp.readlines():
        if "version=" in line:
            version = re.split("\"|'", line)[1]
    if not version:
        raise RuntimeError("Could not detect existing version ... aborting.")
release_version = version.replace(".dev", "")


helper = textwrap.dedent(
    """\
        Start the release process.

        Example:
            setup.py on plugin before script:
                version="2.0.dev"
                requirements = ["pulpcore>=3.4"]


            $ python .ci/scripts/release.py minor 4.0 4.1

            setup.py on plugin after script:
                version="2.1.dev"
                requirements = ["pulpcore>=4.0,<4.1"]

    """
)
parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description=helper)

parser.add_argument(
    "release_type",
    type=str,
    help="Whether the release should be major, minor or patch.",
)

parser.add_argument(
    "--lower", type=str, required=False, help="Lower bound of pulpcore requirement."
)

parser.add_argument(
    "--upper", type=str, required=False, help="Upper bound of pulpcore requirement."
)

args = parser.parse_args()

release_type = args.release_type

if "pulpcore" not in release_path:
    lower_pulpcore_version = args.lower
    upper_pulpcore_version = args.upper

print("\n\nHave you checked the output of: $towncrier --version x.y.z --draft")
print(f"\n\nRepo path: {plugin_path}")
repo = Repo(plugin_path)
git = repo.git

git.checkout("HEAD", b=f"release_{release_version}")

# First commit: changelog
os.system(f"towncrier --yes --version {release_version}")
git.add("CHANGES.rst")
git.add("CHANGES/*")
git.commit("-m", f"Building changelog for {release_version}\n\n[noissue]")

# Second commit: release version
with open(f"{plugin_path}/requirements.txt", "rt") as setup_file:
    setup_lines = setup_file.readlines()

with open(f"{plugin_path}/requirements.txt", "wt") as setup_file:
    for line in setup_lines:
        if "pulpcore" in line and "pulpcore" not in release_path:
            line = f"pulpcore>={lower_pulpcore_version},<{upper_pulpcore_version}\n"

        setup_file.write(line)

os.system("bump2version release --allow-dirty")

git.add(f"{plugin_path}/{plugin_name}/*")
git.add(f"{plugin_path}/docs/conf.py")
git.add(f"{plugin_path}/setup.py")
git.add(f"{plugin_path}/requirements.txt")
git.add(f"{plugin_path}/.bumpversion.cfg")

git.commit("-m", f"Release {release_version}\n\n[noissue]")


sha = repo.head.object.hexsha
short_sha = git.rev_parse(sha, short=7)

# Third commit: bump to .dev
with open(f"{plugin_path}/requirements.txt", "wt") as setup_file:
    for line in setup_lines:
        if "pulpcore" in line and "pulpcore" not in release_path and release_type != "patch":
            line = f"pulpcore>={lower_pulpcore_version}\n"

        setup_file.write(line)

os.system(f"bump2version {release_type} --allow-dirty")

new_dev_version = None
with open(f"{plugin_path}/setup.py") as fp:
    for line in fp.readlines():
        if "version=" in line:
            new_dev_version = re.split("\"|'", line)[1]
    if not new_dev_version:
        raise RuntimeError("Could not detect new dev version ... aborting.")


git.add(f"{plugin_path}/{plugin_name}/*")
git.add(f"{plugin_path}/docs/conf.py")
git.add(f"{plugin_path}/setup.py")
git.add(f"{plugin_path}/requirements.txt")
git.add(f"{plugin_path}/.bumpversion.cfg")
git.commit("-m", f"Bump to {new_dev_version}\n\n[noissue]")


print(f"Release commit == {short_sha}")
print(f"All changes were committed on branch: release_{release_version}")
